# Generated by Django 3.1.2 on 2022-08-09 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, upload_to='photos/userprofilepics')),
                ('description', models.CharField(blank=True, default='', max_length=250)),
                ('full_name', models.CharField(blank=True, default='', max_length=50)),
                ('DOB', models.CharField(blank=True, default='', max_length=20)),
                ('gender', models.CharField(blank=True, default='Male', max_length=10)),
                ('address', models.CharField(blank=True, default='', max_length=200)),
                ('state', models.CharField(blank=True, default='', max_length=20)),
                ('pincode', models.PositiveSmallIntegerField(default=0, null=True)),
                ('category', models.CharField(blank=True, default='', max_length=20)),
                ('marital_status', models.BooleanField(blank=True)),
                ('phone_number', models.PositiveSmallIntegerField(default=0, null=True)),
                ('total_experience', models.FloatField(default=0, null=True)),
                ('skillset', models.CharField(blank=True, default='', max_length=20)),
                ('resume', models.ImageField(blank=True, upload_to='photos/userresume')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.PositiveSmallIntegerField(null=True)),
                ('college_name', models.CharField(blank=True, max_length=250)),
                ('empid_pic', models.ImageField(blank=True, upload_to='photos/empidcardimage')),
                ('location', models.CharField(blank=True, max_length=100)),
                ('website', models.CharField(blank=True, max_length=100)),
                ('director_mail', models.CharField(max_length=30)),
                ('registrar_mail', models.CharField(max_length=30)),
                ('hod_mail', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='college', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('DOB', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('category', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('phone_number', models.PositiveSmallIntegerField(default=0, null=True)),
                ('designation', models.CharField(max_length=250)),
                ('total_experience', models.FloatField(default=0, null=True)),
                ('skillset', models.CharField(blank=True, default='', max_length=20)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='apis.collegeinfomodel')),
            ],
        ),
        migrations.CreateModel(
            name='VacanciesInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('experience', models.CharField(blank=True, max_length=100)),
                ('date_of_posting', models.CharField(blank=True, max_length=20)),
                ('state', models.BooleanField(blank=True, default=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('responsibilities', models.CharField(blank=True, max_length=500)),
                ('qualifications', models.CharField(blank=True, max_length=500)),
                ('skills', models.CharField(blank=True, max_length=200)),
                ('compensation', models.FloatField(null=True)),
                ('applicants', models.ManyToManyField(to='apis.ApplicantInfoModel')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy', to='apis.collegeinfomodel')),
            ],
        ),
        migrations.CreateModel(
            name='RecuitmentCommitteeInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fifth_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fifth_member', to='apis.employeeinfomodel')),
                ('first_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_member', to='apis.employeeinfomodel')),
                ('fourth_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fourth_member', to='apis.employeeinfomodel')),
                ('second_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_member', to='apis.employeeinfomodel')),
                ('third_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_member', to='apis.employeeinfomodel')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee', to='apis.vacanciesinfomodel')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantQualificationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(blank=True, max_length=50)),
                ('marks', models.FloatField(null=True)),
                ('passing_year', models.CharField(blank=True, max_length=20)),
                ('institute', models.CharField(max_length=50)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualification', to='apis.applicantinfomodel')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantExperienceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=20)),
                ('from_date', models.CharField(blank=True, max_length=20)),
                ('to_date', models.CharField(blank=True, max_length=20)),
                ('institute', models.CharField(blank=True, max_length=50)),
                ('details', models.CharField(blank=True, max_length=200)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='apis.applicantinfomodel')),
            ],
        ),
    ]
