# Generated by Django 3.1.2 on 2022-08-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_auto_20220809_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantinfomodel',
            name='DOB',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='applicantinfomodel',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applicantinfomodel',
            name='category',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='applicantinfomodel',
            name='description',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='applicantinfomodel',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='applicantinfomodel',
            name='gender',
            field=models.CharField(blank=True, default='Male', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='applicantinfomodel',
            name='marital_status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicantinfomodel',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='photos/userprofilepics'),
        ),
        migrations.AlterField(
            model_name='applicantinfomodel',
            name='resume',
            field=models.ImageField(blank=True, null=True, upload_to='photos/userresume'),
        ),
        migrations.AlterField(
            model_name='applicantinfomodel',
            name='skillset',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='applicantinfomodel',
            name='state',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
