# Generated by Django 3.1.2 on 2022-08-09 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_remove_collegeinfomodel_college_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicantqualificationmodel',
            old_name='qualification',
            new_name='qualification_name',
        ),
    ]
