# Generated by Django 3.1.2 on 2022-08-09 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_auto_20220810_0019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicantqualificationmodel',
            old_name='qualification_name',
            new_name='qualification_title',
        ),
    ]
