# Generated by Django 3.1.2 on 2022-08-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_auto_20220810_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeinfomodel',
            name='skillset',
        ),
        migrations.RemoveField(
            model_name='employeeinfomodel',
            name='total_experience',
        ),
        migrations.AddField(
            model_name='employeeinfomodel',
            name='status',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='employeeinfomodel',
            name='DOB',
            field=models.CharField(max_length=15),
        ),
    ]
