# Generated by Django 4.1 on 2022-08-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_auto_20220810_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantinfomodel',
            name='profile_pic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applicantinfomodel',
            name='resume',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='collegeinfomodel',
            name='director_mail',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='collegeinfomodel',
            name='empid_pic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='collegeinfomodel',
            name='hod_mail',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='collegeinfomodel',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='collegeinfomodel',
            name='registrar_mail',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='collegeinfomodel',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
