# Generated by Django 3.1.2 on 2022-08-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_auto_20220810_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacanciesinfomodel',
            name='applicants',
        ),
        migrations.AlterField(
            model_name='applicantinfomodel',
            name='profile_pic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applicantinfomodel',
            name='resume',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
